### ISSUE TITLE
Write Test Cases

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-storage-pinning#14]
Complete Test cases for the Pinning smart contracts (Unit testing)

**Comment by AuHau** [comment]
I would say that the basic coverage is already in place, so maybe we could close this? Of course, it is a continuous process, but then I would ask what is the milestone that would close this issue?

**Comment by vojtechsimetka** [comment]
I agree. I will create a different issue which will be "Prepare contract for audit" which has 100% test coverage as subtask :) . (this is actually usually required by auditors)

**Comment by julianmrodri** [comment]
Yes Ill close this one. this is a good amount of testing for a Testnet at least.
