### ISSUE TITLE
File reference can be longer then byte32

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-storage-pinning#16]
IPFS uses Content Identifiers (CID) as hash for referencing some file/data-structure. These CIDs used to be fixed-length (CIDv0 looks like `QmUX5Vcx9eFg4wcEdg77uRkuaot6dnbp7G2qamyV5dpuzt`), but with moving to new version they start being quite flexible on the size, mainly because they support all sort of hashing functions and all sort of encodings.

For details see: https://github.com/multiformats/cid

The default encoding for CIDv1 is base32 which most of the CIDs will look like `bafybeibiqjgj7hh63pwaupjoffmg523nvzwxzbtwpege6by2kfge7ocdwu`

So by default we have to support at least 59 chars hashes, but the length should be either flexible or we should do research on what length we should support.

**Comment by Eknir** [comment]
This is already supported. FileReference is everywhere a `bytes32[]` (array of `bytes32`). Issue can be closed

**Comment by AuHau** [comment]
Great, thanks!
