### ISSUE TITLE
PeerId of Storage Provider

### ISSUE THREAD

**Issue by AuHau** [rsksmart/rif-marketplace-storage-pinning#18]
In order to have some sort of confirmation that file is pinned, we can use the IPFS DHT and its `findProvs` which return a list of providers for specific CID. 

In order for the requester to utilize this mechanic, it needs to know the PeerId of the provider's IPFS node. 

This information does not have to be stored on the blockchain, but can be only emitted as an event and will be cached in the Caching service.

**Comment by Eknir** [comment]
#20 solves this
