### ISSUE TITLE
Rationale for uint64 and uint128 in Periods/Duration

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-storage-pinning#38]
Hi I noticed the contract uses uint128 for the Maximum duration set for an offer, but then for the periods selected for pricing and by the consumer we use uint64. What was the rationale for this decision? Isnt the provider allowed to setup a single long period for the whole duration which in that case price period would need a uint128 value? Maybe im missing something. Thanks!

**Comment by julianmrodri** [comment]
Maybe we can standardise all durations and periods as **uint128** but then limit the maximum duration by the **Maximum duration allowed** variable we want to set up at the contract level and managed by the Owner?

**Comment by AuHau** [comment]
I am not aware of the rationale, that is up to @Eknir to comment on.

**Comment by julianmrodri** [comment]
@AuHau  guess we have unified everything to uint64 right? should we close this issue?

**Comment by AuHau** [comment]
Well not really, but we dropped maximum-duration (from Offer) so yes, lets close this.
