### ISSUE TITLE
Review Available Storage  logic

### ISSUE THREAD

**Issue by julianmrodri** [rsksmart/rif-marketplace-storage-pinning#49]
From @vojtechsimetka  

"I would love to raise one concern here which we talked about before but is even more relevant now when anyone can free up providers storage. Having the `availableStorage` being both the indicator of how much storage provider provides and how much is consumed is rather limiting. Imagine there are 5 agreements and the storage provider wants to stop his services. He sets the `availableStorage` to `0` and waits for the existing agreements to terminate. Now each time an agreement is terminated he needs to as quickly as possible payout the funds and set the `availableStorage` to `0`. Otherwise he risks that someone will start consuming the storage again.

Similar situation happens when he wants to limit the storage capacity. Lets say he provides 1GB, currently 0.75GB is utilised but he wants to as soon as possible limit this storage to 0.5GB. He again needs to set the `availableCapacity` to `0` and after the end of each agreement he needs to do:
```
desiredMaxCapacity = 0.5GB

do {
    consumedCapacity = SUM(agreement.size)
    newAvailableSize = MAX(0, desiredMaxCapacity - consumedCapacity)
} while (newAvailableSize === 0)
```

This is now much bigger issue because anyone can free a capacity of a given provider at any time if some agreements are expired."

**Comment by AuHau** [comment]
Fixed with #50
